# Generated by Django 5.2.8 on 2025-11-09 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='board',
        ),
        migrations.RemoveField(
            model_name='task',
            name='group',
        ),
        migrations.DeleteModel(
            name='Board',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
