# Generated by Django 5.2.8 on 2025-11-17 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='background_image',
            field=models.CharField(default='images/background-default.jpg', max_length=500),
        ),
    ]
