# Generated by Django 5.2.8 on 2025-11-17 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_board_background_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='board_backgrounds/'),
        ),
    ]
